Merged PR 33799: Add null check for changed files to fix Database Build
When we perform a normal merge in Database, the destinationCommit contains the changes of the sourceCommit.

Example commits: 63187f4 update billmodel.billmatter sql to match newer implementation of dbo.hasrowpermission
Source:
Destination: b0a32fe Merged PR 33337: Merge 8 deux, due, dos, dois, dva to master

Therefore, the changes come up as null, which throws the following error:

`The "GetPropertiesFromContext" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null. `

Therefore, added a null check for changed files to fix Database Build.

[Test-Database-Build](https://tfs.aderant.com/tfs/ADERANT/ExpertSuite/ExpertSuite%20Team/_build/index?buildId=1115632&_a=summary)

Related work items: #243764