Merged PR 37869: Register correct VS2015 path for Text Templating
Register correct VS2015 path for text templating.

### Issue
The current path is incorrect which prevents resolving the ```Microsoft.VisualStudio.Modeling.Sdk.DslDefinition.14.0``` Visual Studio 2015 assembly which is not in the GAC.
```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Modeling.Sdk.DslDefinition.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

### Test
Successful build of the branch exhibiting the issue:
https://tfs.aderant.com/tfs/ADERANT/ExpertSuite/_build/index?buildId=1146723

Related work items: #253741